services:
  - type: web
    name: expense-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npm rebuild better-sqlite3
    startCommand: node src/server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: JWT_SECRET
        generateValue: true
      - key: DB_FILE
        value: /var/data/app.db
    disks:
      - name: data
        mountPath: /var/data
        sizeGB: 1
    healthCheckPath: /api/health

  - type: static
    name: expense-frontend
    rootDir: frontend/app
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: expense-backend
          type: web
          property: host

